[project]
name = "maarco"
version = "0.1.0"
description = "Code for MAARCO"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygpsclient>=1.5.14",
    "pynmeagps>=1.0.53",
    "pyrtcm>=1.1.9",
    "rpi-hardware-pwm>=0.3.0",
    "textual>=6.3.0",
    "textual-dev>=1.8.0",
    "textual-speedups>=0.2.0",
    "pyserial>=3.5",
    "numpy>=2.1.0",        # For np.polyfit, np.fft, etc.
    "pandas>=2.2.0",       # For feature DataFrames
    "scipy>=1.13.0",       # For savgol_filter and periodogram
    "joblib>=1.4.0",       # For loading your .pkl models
    "scikit-learn>=1.5.0", # Required because joblib loads sklearn models
]